version: '3.8'

networks:
  test-net:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

configs:
  nginx_config:
    file: ./nginx/nginx.conf
  prometheus_config:
    file: ./prometheus/prometheus.yml

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
    networks:
      - test-net

  web:
    image: test-environment-web:latest
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=testdb
      - REDIS_HOST=cache
    networks:
      - test-net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    networks:
      - test-net

  cache:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    deploy:
      replicas: 1
    networks:
      - test-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    deploy:
      replicas: 1
    networks:
      - test-net

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
    networks:
      - test-net