version: '3.8'

# СЕТИ (overlay для Swarm)
networks:
  test-net:
    driver: overlay
    attachable: true

# ТОМА (хранилища)
volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# КОНФИГУРАЦИИ (только для Swarm)
configs:
  nginx_config:
    file: ./nginx/nginx.conf
  prometheus_config:
    file: ./prometheus/prometheus.yml

# СЕРВИСЫ
services:
  # 1. NGINX (веб-сервер, прокси)
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - test-net

  # 2. WEB APP (наше приложение с фронтендом)
  web:
    image: test-environment-web:latest  # Локальный образ
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=testdb
      - REDIS_HOST=cache
    networks:
      - test-net

  # 3. DATABASE (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      # placement:  
      #   constraints:
      #     - node.labels.type == database
    networks:
      - test-net

  # 4. CACHE (Redis)
  cache:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - test-net

  # 5. MONITORING (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - test-net

  # 6. MONITORING (Grafana)
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - test-net